// Vendors a named subset of Bootstrap Icons (twbs/icons, MIT) into `src/icons.gen.ts`.
//
// Generated rather than imported at runtime: the webview CSP is `default-src 'self'` (no
// CDN); `npm test` runs the source through node, not Vite, so `?raw` SVG imports would
// break the tests; and we use ~24 of 2078 icons. The package is a devDependency for
// provenance and upgrades.
//
//   node --experimental-strip-types scripts/gen-icons.ts            # regenerate (make icons)
//   node --experimental-strip-types scripts/gen-icons.ts --check    # fail if stale
//
// `--check` runs first in `npm test`, so bumping the dependency fails the gate until the
// file is regenerated.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, "..", "node_modules", "bootstrap-icons");
const OUT = join(HERE, "..", "src", "icons.gen.ts");

/**
 * The subset, grouped by what asks for it. To add an icon: name it here, `make icons`, use
 * it (`IconName` is `keyof typeof ICON_BODIES`, so a typo is a type error).
 */
const MANIFEST: Record<string, readonly string[]> = {
  // `chevron-right`/`-down` are the app's one fold affordance; `-left`/`-up` are history
  // back and find-previous.
  chevrons: ["chevron-down", "chevron-left", "chevron-right", "chevron-up"],

  // The file tree: a folder's open/closed state, and one icon per file class.
  tree: [
    "file-earmark-binary",
    "file-earmark-code",
    "file-earmark-font",
    "file-earmark-image",
    "file-earmark-pdf",
    "file-earmark-play",
    "file-earmark-text",
    "folder",
    "folder2-open",
  ],

  // Create actions (tree head) and the top bar; `chat-dots` is the chat toggle (GH #155).
  actions: ["chat-dots", "file-earmark-plus", "folder-plus", "gear", "search", "x-lg"],

  // Note-bar toggles: the connection graph and the Markdown-source view.
  toggles: ["code-slash", "diagram-3"],

  // Status: faults take the triangle; notices (ungraded discovery, raw mode) take
  // `info-circle`.
  status: ["exclamation-triangle", "info-circle", "stars"],

  // The Explain view's "?" (GH #236).
  help: ["question-circle"],

  // A connection's direction, on the discovery card that names it.
  edges: ["arrow-left", "arrow-right"],
};

const NAMES = Object.values(MANIFEST).flat().sort();

/**
 * An icon file's children (between `<svg …>` and `</svg>`), whitespace collapsed. The
 * wrapper is `icon()`'s, so upstream's `width` and `class` stay out of call sites.
 */
export function iconBody(svg: string): string {
  const open = svg.indexOf(">");
  const close = svg.lastIndexOf("</svg>");
  if (!svg.startsWith("<svg") || open === -1 || close === -1) {
    throw new Error("not an <svg> document");
  }
  return svg.slice(open + 1, close).replace(/\s+/g, " ").trim();
}

function read(name: string): string {
  const body = iconBody(readFileSync(join(PKG, "icons", `${name}.svg`), "utf8"));
  // Upstream ships static shapes; anything else would be arriving in our bundle unread.
  if (/<(script|style|image|foreignObject)\b/i.test(body)) {
    throw new Error(`${name}: unexpected element in upstream icon`);
  }
  return body;
}

/**
 * The upstream license, verbatim. MIT requires the copyright and permission notice to travel
 * with the vendored path data, so it is emitted twice: as a `/*!` legal comment (which
 * esbuild keeps, so it reaches `ui/dist`) and as an exported string that `icons.test.ts`
 * asserts (`--check` alone would pass a generator edited to drop it).
 */
const LICENSE_TEXT = `The MIT License (MIT)

Copyright (c) 2019-2024 The Bootstrap Authors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

function generate(): string {
  const version = JSON.parse(readFileSync(join(PKG, "package.json"), "utf8")).version;
  const rows = NAMES.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(read(n))},`);
  return `// @generated by scripts/gen-icons.ts — do not edit. Run \`make icons\` to refresh.
//
// The subset is declared in scripts/gen-icons.ts; the wrapper, the sizes and the semantic
// name → meaning maps are in src/icons.ts. Nothing but the generator writes this file.

/*!
 * Bootstrap Icons v${version} — https://github.com/twbs/icons
 * @license MIT
 *
${LICENSE_TEXT.split("\n")
  .map((l) => ` * ${l}`.trimEnd())
  .join("\n")}
 */

/** Each icon's children — the markup \`icon()\` wraps in its own sized \`<svg>\`. */
export const ICON_BODIES = {
${rows.join("\n")}
} as const;

/** The upstream release this data was lifted from. \`gen-icons.ts --check\` pins it. */
export const BOOTSTRAP_ICONS_VERSION = ${JSON.stringify(version)};

/** The terms the data above is used under — see the generator for why this is a value and
 *  not only a comment. \`icons.test.ts\` asserts the notice is intact. */
export const BOOTSTRAP_ICONS_LICENSE = ${JSON.stringify(LICENSE_TEXT)};
`;
}

const next = generate();

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current !== next) {
    console.error(
      "src/icons.gen.ts is stale — bootstrap-icons changed, or it was hand-edited.\n" +
        "Run `make icons` (or `npm --prefix ui run icons`) and commit the result.",
    );
    process.exit(1);
  }
  console.log(`  ok  src/icons.gen.ts matches bootstrap-icons (${NAMES.length} icons)`);
} else {
  writeFileSync(OUT, next);
  console.log(`wrote src/icons.gen.ts — ${NAMES.length} icons`);
}
